// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fit_fit,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7s100-fgga676-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.030000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=19,HLS_SYN_DSP=0,HLS_SYN_FF=55825,HLS_SYN_LUT=41606,HLS_VERSION=2023_1}" *)

module fit (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        input_r_TDATA,
        output_r_TDATA,
        input_r_TVALID,
        input_r_TREADY,
        output_r_TVALID,
        output_r_TREADY
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [63:0] input_r_TDATA;
output  [383:0] output_r_TDATA;
input   input_r_TVALID;
output   input_r_TREADY;
output   output_r_TVALID;
input   output_r_TREADY;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_continue;
wire    ap_idle;
wire    readStage_U0_ap_start;
wire    readStage_U0_start_full_n;
wire    readStage_U0_ap_done;
wire    readStage_U0_ap_continue;
wire    readStage_U0_ap_idle;
wire    readStage_U0_ap_ready;
wire   [11:0] readStage_U0_x1_din;
wire    readStage_U0_x1_write;
wire   [11:0] readStage_U0_x2_din;
wire    readStage_U0_x2_write;
wire   [11:0] readStage_U0_y1_din;
wire    readStage_U0_y1_write;
wire   [11:0] readStage_U0_y2_din;
wire    readStage_U0_y2_write;
wire   [63:0] readStage_U0_sigmaDiv1_din;
wire    readStage_U0_sigmaDiv1_write;
wire   [63:0] readStage_U0_sigmaSquaredDiv1_din;
wire    readStage_U0_sigmaSquaredDiv1_write;
wire   [1:0] readStage_U0_last1_din;
wire    readStage_U0_last1_write;
wire   [1:0] readStage_U0_last2_din;
wire    readStage_U0_last2_write;
wire   [1:0] readStage_U0_last3_din;
wire    readStage_U0_last3_write;
wire   [63:0] readStage_U0_partialS_din;
wire    readStage_U0_partialS_write;
wire   [63:0] readStage_U0_partialSx_din;
wire    readStage_U0_partialSx_write;
wire   [63:0] readStage_U0_partialSy_din;
wire    readStage_U0_partialSy_write;
wire    readStage_U0_start_out;
wire    readStage_U0_start_write;
wire    readStage_U0_input_r_TREADY;
wire    interStage1_U0_ap_start;
wire    interStage1_U0_ap_done;
wire    interStage1_U0_ap_continue;
wire    interStage1_U0_ap_idle;
wire    interStage1_U0_ap_ready;
wire    interStage1_U0_partialS_read;
wire    interStage1_U0_partialSx_read;
wire    interStage1_U0_partialSy_read;
wire    interStage1_U0_last1_read;
wire   [63:0] interStage1_U0_SDiv1_din;
wire    interStage1_U0_SDiv1_write;
wire   [63:0] interStage1_U0_SxDivS_din;
wire    interStage1_U0_SxDivS_write;
wire   [63:0] interStage1_U0_SxSquaredDivS_din;
wire    interStage1_U0_SxSquaredDivS_write;
wire   [63:0] interStage1_U0_SyDivS_din;
wire    interStage1_U0_SyDivS_write;
wire    interStage2_U0_ap_start;
wire    interStage2_U0_ap_done;
wire    interStage2_U0_ap_continue;
wire    interStage2_U0_ap_idle;
wire    interStage2_U0_ap_ready;
wire    interStage2_U0_x1_read;
wire    interStage2_U0_y1_read;
wire    interStage2_U0_sigmaDiv1_read;
wire    interStage2_U0_SDiv1_read;
wire    interStage2_U0_SxDivS_read;
wire    interStage2_U0_SxSquaredDivS_read;
wire    interStage2_U0_SyDivS_read;
wire    interStage2_U0_last2_read;
wire   [331:0] interStage2_U0_resultStream_din;
wire    interStage2_U0_resultStream_write;
wire    finalStage_U0_ap_start;
wire    finalStage_U0_ap_done;
wire    finalStage_U0_ap_continue;
wire    finalStage_U0_ap_idle;
wire    finalStage_U0_ap_ready;
wire    finalStage_U0_resultStream_read;
wire    finalStage_U0_x2_read;
wire    finalStage_U0_y2_read;
wire    finalStage_U0_sigmaSquaredDiv1_read;
wire    finalStage_U0_last3_read;
wire   [383:0] finalStage_U0_output_r_TDATA;
wire    finalStage_U0_output_r_TVALID;
wire    partialS_full_n;
wire   [63:0] partialS_dout;
wire   [4:0] partialS_num_data_valid;
wire   [4:0] partialS_fifo_cap;
wire    partialS_empty_n;
wire    partialSx_full_n;
wire   [63:0] partialSx_dout;
wire   [4:0] partialSx_num_data_valid;
wire   [4:0] partialSx_fifo_cap;
wire    partialSx_empty_n;
wire    partialSy_full_n;
wire   [63:0] partialSy_dout;
wire   [4:0] partialSy_num_data_valid;
wire   [4:0] partialSy_fifo_cap;
wire    partialSy_empty_n;
wire    x1_full_n;
wire   [11:0] x1_dout;
wire   [4:0] x1_num_data_valid;
wire   [4:0] x1_fifo_cap;
wire    x1_empty_n;
wire    x2_full_n;
wire   [11:0] x2_dout;
wire   [4:0] x2_num_data_valid;
wire   [4:0] x2_fifo_cap;
wire    x2_empty_n;
wire    y1_full_n;
wire   [11:0] y1_dout;
wire   [4:0] y1_num_data_valid;
wire   [4:0] y1_fifo_cap;
wire    y1_empty_n;
wire    y2_full_n;
wire   [11:0] y2_dout;
wire   [4:0] y2_num_data_valid;
wire   [4:0] y2_fifo_cap;
wire    y2_empty_n;
wire    sigmaDiv1_full_n;
wire   [63:0] sigmaDiv1_dout;
wire   [4:0] sigmaDiv1_num_data_valid;
wire   [4:0] sigmaDiv1_fifo_cap;
wire    sigmaDiv1_empty_n;
wire    sigmaSquaredDiv1_full_n;
wire   [63:0] sigmaSquaredDiv1_dout;
wire   [4:0] sigmaSquaredDiv1_num_data_valid;
wire   [4:0] sigmaSquaredDiv1_fifo_cap;
wire    sigmaSquaredDiv1_empty_n;
wire    last1_full_n;
wire   [1:0] last1_dout;
wire   [4:0] last1_num_data_valid;
wire   [4:0] last1_fifo_cap;
wire    last1_empty_n;
wire    last2_full_n;
wire   [1:0] last2_dout;
wire   [4:0] last2_num_data_valid;
wire   [4:0] last2_fifo_cap;
wire    last2_empty_n;
wire    last3_full_n;
wire   [1:0] last3_dout;
wire   [4:0] last3_num_data_valid;
wire   [4:0] last3_fifo_cap;
wire    last3_empty_n;
wire    SDiv1_full_n;
wire   [63:0] SDiv1_dout;
wire   [4:0] SDiv1_num_data_valid;
wire   [4:0] SDiv1_fifo_cap;
wire    SDiv1_empty_n;
wire    SxDivS_full_n;
wire   [63:0] SxDivS_dout;
wire   [4:0] SxDivS_num_data_valid;
wire   [4:0] SxDivS_fifo_cap;
wire    SxDivS_empty_n;
wire    SxSquaredDivS_full_n;
wire   [63:0] SxSquaredDivS_dout;
wire   [4:0] SxSquaredDivS_num_data_valid;
wire   [4:0] SxSquaredDivS_fifo_cap;
wire    SxSquaredDivS_empty_n;
wire    SyDivS_full_n;
wire   [63:0] SyDivS_dout;
wire   [4:0] SyDivS_num_data_valid;
wire   [4:0] SyDivS_fifo_cap;
wire    SyDivS_empty_n;
wire    resultStream_full_n;
wire   [331:0] resultStream_dout;
wire   [4:0] resultStream_num_data_valid;
wire   [4:0] resultStream_fifo_cap;
wire    resultStream_empty_n;
wire   [0:0] start_for_interStage1_U0_din;
wire    start_for_interStage1_U0_full_n;
wire   [0:0] start_for_interStage1_U0_dout;
wire    start_for_interStage1_U0_empty_n;
wire   [0:0] start_for_interStage2_U0_din;
wire    start_for_interStage2_U0_full_n;
wire   [0:0] start_for_interStage2_U0_dout;
wire    start_for_interStage2_U0_empty_n;
wire   [0:0] start_for_finalStage_U0_din;
wire    start_for_finalStage_U0_full_n;
wire   [0:0] start_for_finalStage_U0_dout;
wire    start_for_finalStage_U0_empty_n;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
end

fit_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

fit_readStage readStage_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(readStage_U0_ap_start),
    .start_full_n(readStage_U0_start_full_n),
    .ap_done(readStage_U0_ap_done),
    .ap_continue(readStage_U0_ap_continue),
    .ap_idle(readStage_U0_ap_idle),
    .ap_ready(readStage_U0_ap_ready),
    .input_r_TVALID(input_r_TVALID),
    .x1_din(readStage_U0_x1_din),
    .x1_num_data_valid(x1_num_data_valid),
    .x1_fifo_cap(x1_fifo_cap),
    .x1_full_n(x1_full_n),
    .x1_write(readStage_U0_x1_write),
    .x2_din(readStage_U0_x2_din),
    .x2_num_data_valid(x2_num_data_valid),
    .x2_fifo_cap(x2_fifo_cap),
    .x2_full_n(x2_full_n),
    .x2_write(readStage_U0_x2_write),
    .y1_din(readStage_U0_y1_din),
    .y1_num_data_valid(y1_num_data_valid),
    .y1_fifo_cap(y1_fifo_cap),
    .y1_full_n(y1_full_n),
    .y1_write(readStage_U0_y1_write),
    .y2_din(readStage_U0_y2_din),
    .y2_num_data_valid(y2_num_data_valid),
    .y2_fifo_cap(y2_fifo_cap),
    .y2_full_n(y2_full_n),
    .y2_write(readStage_U0_y2_write),
    .sigmaDiv1_din(readStage_U0_sigmaDiv1_din),
    .sigmaDiv1_num_data_valid(sigmaDiv1_num_data_valid),
    .sigmaDiv1_fifo_cap(sigmaDiv1_fifo_cap),
    .sigmaDiv1_full_n(sigmaDiv1_full_n),
    .sigmaDiv1_write(readStage_U0_sigmaDiv1_write),
    .sigmaSquaredDiv1_din(readStage_U0_sigmaSquaredDiv1_din),
    .sigmaSquaredDiv1_num_data_valid(sigmaSquaredDiv1_num_data_valid),
    .sigmaSquaredDiv1_fifo_cap(sigmaSquaredDiv1_fifo_cap),
    .sigmaSquaredDiv1_full_n(sigmaSquaredDiv1_full_n),
    .sigmaSquaredDiv1_write(readStage_U0_sigmaSquaredDiv1_write),
    .last1_din(readStage_U0_last1_din),
    .last1_num_data_valid(last1_num_data_valid),
    .last1_fifo_cap(last1_fifo_cap),
    .last1_full_n(last1_full_n),
    .last1_write(readStage_U0_last1_write),
    .last2_din(readStage_U0_last2_din),
    .last2_num_data_valid(last2_num_data_valid),
    .last2_fifo_cap(last2_fifo_cap),
    .last2_full_n(last2_full_n),
    .last2_write(readStage_U0_last2_write),
    .last3_din(readStage_U0_last3_din),
    .last3_num_data_valid(last3_num_data_valid),
    .last3_fifo_cap(last3_fifo_cap),
    .last3_full_n(last3_full_n),
    .last3_write(readStage_U0_last3_write),
    .partialS_din(readStage_U0_partialS_din),
    .partialS_num_data_valid(partialS_num_data_valid),
    .partialS_fifo_cap(partialS_fifo_cap),
    .partialS_full_n(partialS_full_n),
    .partialS_write(readStage_U0_partialS_write),
    .partialSx_din(readStage_U0_partialSx_din),
    .partialSx_num_data_valid(partialSx_num_data_valid),
    .partialSx_fifo_cap(partialSx_fifo_cap),
    .partialSx_full_n(partialSx_full_n),
    .partialSx_write(readStage_U0_partialSx_write),
    .partialSy_din(readStage_U0_partialSy_din),
    .partialSy_num_data_valid(partialSy_num_data_valid),
    .partialSy_fifo_cap(partialSy_fifo_cap),
    .partialSy_full_n(partialSy_full_n),
    .partialSy_write(readStage_U0_partialSy_write),
    .start_out(readStage_U0_start_out),
    .start_write(readStage_U0_start_write),
    .input_r_TDATA(input_r_TDATA),
    .input_r_TREADY(readStage_U0_input_r_TREADY)
);

fit_interStage1 interStage1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(interStage1_U0_ap_start),
    .ap_done(interStage1_U0_ap_done),
    .ap_continue(interStage1_U0_ap_continue),
    .ap_idle(interStage1_U0_ap_idle),
    .ap_ready(interStage1_U0_ap_ready),
    .partialS_dout(partialS_dout),
    .partialS_num_data_valid(partialS_num_data_valid),
    .partialS_fifo_cap(partialS_fifo_cap),
    .partialS_empty_n(partialS_empty_n),
    .partialS_read(interStage1_U0_partialS_read),
    .partialSx_dout(partialSx_dout),
    .partialSx_num_data_valid(partialSx_num_data_valid),
    .partialSx_fifo_cap(partialSx_fifo_cap),
    .partialSx_empty_n(partialSx_empty_n),
    .partialSx_read(interStage1_U0_partialSx_read),
    .partialSy_dout(partialSy_dout),
    .partialSy_num_data_valid(partialSy_num_data_valid),
    .partialSy_fifo_cap(partialSy_fifo_cap),
    .partialSy_empty_n(partialSy_empty_n),
    .partialSy_read(interStage1_U0_partialSy_read),
    .last1_dout(last1_dout),
    .last1_num_data_valid(last1_num_data_valid),
    .last1_fifo_cap(last1_fifo_cap),
    .last1_empty_n(last1_empty_n),
    .last1_read(interStage1_U0_last1_read),
    .SDiv1_din(interStage1_U0_SDiv1_din),
    .SDiv1_num_data_valid(SDiv1_num_data_valid),
    .SDiv1_fifo_cap(SDiv1_fifo_cap),
    .SDiv1_full_n(SDiv1_full_n),
    .SDiv1_write(interStage1_U0_SDiv1_write),
    .SxDivS_din(interStage1_U0_SxDivS_din),
    .SxDivS_num_data_valid(SxDivS_num_data_valid),
    .SxDivS_fifo_cap(SxDivS_fifo_cap),
    .SxDivS_full_n(SxDivS_full_n),
    .SxDivS_write(interStage1_U0_SxDivS_write),
    .SxSquaredDivS_din(interStage1_U0_SxSquaredDivS_din),
    .SxSquaredDivS_num_data_valid(SxSquaredDivS_num_data_valid),
    .SxSquaredDivS_fifo_cap(SxSquaredDivS_fifo_cap),
    .SxSquaredDivS_full_n(SxSquaredDivS_full_n),
    .SxSquaredDivS_write(interStage1_U0_SxSquaredDivS_write),
    .SyDivS_din(interStage1_U0_SyDivS_din),
    .SyDivS_num_data_valid(SyDivS_num_data_valid),
    .SyDivS_fifo_cap(SyDivS_fifo_cap),
    .SyDivS_full_n(SyDivS_full_n),
    .SyDivS_write(interStage1_U0_SyDivS_write)
);

fit_interStage2 interStage2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(interStage2_U0_ap_start),
    .ap_done(interStage2_U0_ap_done),
    .ap_continue(interStage2_U0_ap_continue),
    .ap_idle(interStage2_U0_ap_idle),
    .ap_ready(interStage2_U0_ap_ready),
    .x1_dout(x1_dout),
    .x1_num_data_valid(x1_num_data_valid),
    .x1_fifo_cap(x1_fifo_cap),
    .x1_empty_n(x1_empty_n),
    .x1_read(interStage2_U0_x1_read),
    .y1_dout(y1_dout),
    .y1_num_data_valid(y1_num_data_valid),
    .y1_fifo_cap(y1_fifo_cap),
    .y1_empty_n(y1_empty_n),
    .y1_read(interStage2_U0_y1_read),
    .sigmaDiv1_dout(sigmaDiv1_dout),
    .sigmaDiv1_num_data_valid(sigmaDiv1_num_data_valid),
    .sigmaDiv1_fifo_cap(sigmaDiv1_fifo_cap),
    .sigmaDiv1_empty_n(sigmaDiv1_empty_n),
    .sigmaDiv1_read(interStage2_U0_sigmaDiv1_read),
    .SDiv1_dout(SDiv1_dout),
    .SDiv1_num_data_valid(SDiv1_num_data_valid),
    .SDiv1_fifo_cap(SDiv1_fifo_cap),
    .SDiv1_empty_n(SDiv1_empty_n),
    .SDiv1_read(interStage2_U0_SDiv1_read),
    .SxDivS_dout(SxDivS_dout),
    .SxDivS_num_data_valid(SxDivS_num_data_valid),
    .SxDivS_fifo_cap(SxDivS_fifo_cap),
    .SxDivS_empty_n(SxDivS_empty_n),
    .SxDivS_read(interStage2_U0_SxDivS_read),
    .SxSquaredDivS_dout(SxSquaredDivS_dout),
    .SxSquaredDivS_num_data_valid(SxSquaredDivS_num_data_valid),
    .SxSquaredDivS_fifo_cap(SxSquaredDivS_fifo_cap),
    .SxSquaredDivS_empty_n(SxSquaredDivS_empty_n),
    .SxSquaredDivS_read(interStage2_U0_SxSquaredDivS_read),
    .SyDivS_dout(SyDivS_dout),
    .SyDivS_num_data_valid(SyDivS_num_data_valid),
    .SyDivS_fifo_cap(SyDivS_fifo_cap),
    .SyDivS_empty_n(SyDivS_empty_n),
    .SyDivS_read(interStage2_U0_SyDivS_read),
    .last2_dout(last2_dout),
    .last2_num_data_valid(last2_num_data_valid),
    .last2_fifo_cap(last2_fifo_cap),
    .last2_empty_n(last2_empty_n),
    .last2_read(interStage2_U0_last2_read),
    .resultStream_din(interStage2_U0_resultStream_din),
    .resultStream_num_data_valid(resultStream_num_data_valid),
    .resultStream_fifo_cap(resultStream_fifo_cap),
    .resultStream_full_n(resultStream_full_n),
    .resultStream_write(interStage2_U0_resultStream_write)
);

fit_finalStage finalStage_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(finalStage_U0_ap_start),
    .ap_done(finalStage_U0_ap_done),
    .ap_continue(finalStage_U0_ap_continue),
    .ap_idle(finalStage_U0_ap_idle),
    .ap_ready(finalStage_U0_ap_ready),
    .resultStream_dout(resultStream_dout),
    .resultStream_num_data_valid(resultStream_num_data_valid),
    .resultStream_fifo_cap(resultStream_fifo_cap),
    .resultStream_empty_n(resultStream_empty_n),
    .resultStream_read(finalStage_U0_resultStream_read),
    .x2_dout(x2_dout),
    .x2_num_data_valid(x2_num_data_valid),
    .x2_fifo_cap(x2_fifo_cap),
    .x2_empty_n(x2_empty_n),
    .x2_read(finalStage_U0_x2_read),
    .y2_dout(y2_dout),
    .y2_num_data_valid(y2_num_data_valid),
    .y2_fifo_cap(y2_fifo_cap),
    .y2_empty_n(y2_empty_n),
    .y2_read(finalStage_U0_y2_read),
    .sigmaSquaredDiv1_dout(sigmaSquaredDiv1_dout),
    .sigmaSquaredDiv1_num_data_valid(sigmaSquaredDiv1_num_data_valid),
    .sigmaSquaredDiv1_fifo_cap(sigmaSquaredDiv1_fifo_cap),
    .sigmaSquaredDiv1_empty_n(sigmaSquaredDiv1_empty_n),
    .sigmaSquaredDiv1_read(finalStage_U0_sigmaSquaredDiv1_read),
    .last3_dout(last3_dout),
    .last3_num_data_valid(last3_num_data_valid),
    .last3_fifo_cap(last3_fifo_cap),
    .last3_empty_n(last3_empty_n),
    .last3_read(finalStage_U0_last3_read),
    .output_r_TDATA(finalStage_U0_output_r_TDATA),
    .output_r_TVALID(finalStage_U0_output_r_TVALID),
    .output_r_TREADY(output_r_TREADY)
);

fit_fifo_w64_d10_S partialS_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(readStage_U0_partialS_din),
    .if_full_n(partialS_full_n),
    .if_write(readStage_U0_partialS_write),
    .if_dout(partialS_dout),
    .if_num_data_valid(partialS_num_data_valid),
    .if_fifo_cap(partialS_fifo_cap),
    .if_empty_n(partialS_empty_n),
    .if_read(interStage1_U0_partialS_read)
);

fit_fifo_w64_d10_S partialSx_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(readStage_U0_partialSx_din),
    .if_full_n(partialSx_full_n),
    .if_write(readStage_U0_partialSx_write),
    .if_dout(partialSx_dout),
    .if_num_data_valid(partialSx_num_data_valid),
    .if_fifo_cap(partialSx_fifo_cap),
    .if_empty_n(partialSx_empty_n),
    .if_read(interStage1_U0_partialSx_read)
);

fit_fifo_w64_d10_S partialSy_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(readStage_U0_partialSy_din),
    .if_full_n(partialSy_full_n),
    .if_write(readStage_U0_partialSy_write),
    .if_dout(partialSy_dout),
    .if_num_data_valid(partialSy_num_data_valid),
    .if_fifo_cap(partialSy_fifo_cap),
    .if_empty_n(partialSy_empty_n),
    .if_read(interStage1_U0_partialSy_read)
);

fit_fifo_w12_d10_S x1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(readStage_U0_x1_din),
    .if_full_n(x1_full_n),
    .if_write(readStage_U0_x1_write),
    .if_dout(x1_dout),
    .if_num_data_valid(x1_num_data_valid),
    .if_fifo_cap(x1_fifo_cap),
    .if_empty_n(x1_empty_n),
    .if_read(interStage2_U0_x1_read)
);

fit_fifo_w12_d10_S x2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(readStage_U0_x2_din),
    .if_full_n(x2_full_n),
    .if_write(readStage_U0_x2_write),
    .if_dout(x2_dout),
    .if_num_data_valid(x2_num_data_valid),
    .if_fifo_cap(x2_fifo_cap),
    .if_empty_n(x2_empty_n),
    .if_read(finalStage_U0_x2_read)
);

fit_fifo_w12_d10_S y1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(readStage_U0_y1_din),
    .if_full_n(y1_full_n),
    .if_write(readStage_U0_y1_write),
    .if_dout(y1_dout),
    .if_num_data_valid(y1_num_data_valid),
    .if_fifo_cap(y1_fifo_cap),
    .if_empty_n(y1_empty_n),
    .if_read(interStage2_U0_y1_read)
);

fit_fifo_w12_d10_S y2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(readStage_U0_y2_din),
    .if_full_n(y2_full_n),
    .if_write(readStage_U0_y2_write),
    .if_dout(y2_dout),
    .if_num_data_valid(y2_num_data_valid),
    .if_fifo_cap(y2_fifo_cap),
    .if_empty_n(y2_empty_n),
    .if_read(finalStage_U0_y2_read)
);

fit_fifo_w64_d10_S sigmaDiv1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(readStage_U0_sigmaDiv1_din),
    .if_full_n(sigmaDiv1_full_n),
    .if_write(readStage_U0_sigmaDiv1_write),
    .if_dout(sigmaDiv1_dout),
    .if_num_data_valid(sigmaDiv1_num_data_valid),
    .if_fifo_cap(sigmaDiv1_fifo_cap),
    .if_empty_n(sigmaDiv1_empty_n),
    .if_read(interStage2_U0_sigmaDiv1_read)
);

fit_fifo_w64_d10_S sigmaSquaredDiv1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(readStage_U0_sigmaSquaredDiv1_din),
    .if_full_n(sigmaSquaredDiv1_full_n),
    .if_write(readStage_U0_sigmaSquaredDiv1_write),
    .if_dout(sigmaSquaredDiv1_dout),
    .if_num_data_valid(sigmaSquaredDiv1_num_data_valid),
    .if_fifo_cap(sigmaSquaredDiv1_fifo_cap),
    .if_empty_n(sigmaSquaredDiv1_empty_n),
    .if_read(finalStage_U0_sigmaSquaredDiv1_read)
);

fit_fifo_w2_d10_S last1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(readStage_U0_last1_din),
    .if_full_n(last1_full_n),
    .if_write(readStage_U0_last1_write),
    .if_dout(last1_dout),
    .if_num_data_valid(last1_num_data_valid),
    .if_fifo_cap(last1_fifo_cap),
    .if_empty_n(last1_empty_n),
    .if_read(interStage1_U0_last1_read)
);

fit_fifo_w2_d10_S last2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(readStage_U0_last2_din),
    .if_full_n(last2_full_n),
    .if_write(readStage_U0_last2_write),
    .if_dout(last2_dout),
    .if_num_data_valid(last2_num_data_valid),
    .if_fifo_cap(last2_fifo_cap),
    .if_empty_n(last2_empty_n),
    .if_read(interStage2_U0_last2_read)
);

fit_fifo_w2_d10_S last3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(readStage_U0_last3_din),
    .if_full_n(last3_full_n),
    .if_write(readStage_U0_last3_write),
    .if_dout(last3_dout),
    .if_num_data_valid(last3_num_data_valid),
    .if_fifo_cap(last3_fifo_cap),
    .if_empty_n(last3_empty_n),
    .if_read(finalStage_U0_last3_read)
);

fit_fifo_w64_d10_S SDiv1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(interStage1_U0_SDiv1_din),
    .if_full_n(SDiv1_full_n),
    .if_write(interStage1_U0_SDiv1_write),
    .if_dout(SDiv1_dout),
    .if_num_data_valid(SDiv1_num_data_valid),
    .if_fifo_cap(SDiv1_fifo_cap),
    .if_empty_n(SDiv1_empty_n),
    .if_read(interStage2_U0_SDiv1_read)
);

fit_fifo_w64_d10_S SxDivS_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(interStage1_U0_SxDivS_din),
    .if_full_n(SxDivS_full_n),
    .if_write(interStage1_U0_SxDivS_write),
    .if_dout(SxDivS_dout),
    .if_num_data_valid(SxDivS_num_data_valid),
    .if_fifo_cap(SxDivS_fifo_cap),
    .if_empty_n(SxDivS_empty_n),
    .if_read(interStage2_U0_SxDivS_read)
);

fit_fifo_w64_d10_S SxSquaredDivS_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(interStage1_U0_SxSquaredDivS_din),
    .if_full_n(SxSquaredDivS_full_n),
    .if_write(interStage1_U0_SxSquaredDivS_write),
    .if_dout(SxSquaredDivS_dout),
    .if_num_data_valid(SxSquaredDivS_num_data_valid),
    .if_fifo_cap(SxSquaredDivS_fifo_cap),
    .if_empty_n(SxSquaredDivS_empty_n),
    .if_read(interStage2_U0_SxSquaredDivS_read)
);

fit_fifo_w64_d10_S SyDivS_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(interStage1_U0_SyDivS_din),
    .if_full_n(SyDivS_full_n),
    .if_write(interStage1_U0_SyDivS_write),
    .if_dout(SyDivS_dout),
    .if_num_data_valid(SyDivS_num_data_valid),
    .if_fifo_cap(SyDivS_fifo_cap),
    .if_empty_n(SyDivS_empty_n),
    .if_read(interStage2_U0_SyDivS_read)
);

fit_fifo_w332_d10_A resultStream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(interStage2_U0_resultStream_din),
    .if_full_n(resultStream_full_n),
    .if_write(interStage2_U0_resultStream_write),
    .if_dout(resultStream_dout),
    .if_num_data_valid(resultStream_num_data_valid),
    .if_fifo_cap(resultStream_fifo_cap),
    .if_empty_n(resultStream_empty_n),
    .if_read(finalStage_U0_resultStream_read)
);

fit_start_for_interStage1_U0 start_for_interStage1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_interStage1_U0_din),
    .if_full_n(start_for_interStage1_U0_full_n),
    .if_write(readStage_U0_start_write),
    .if_dout(start_for_interStage1_U0_dout),
    .if_empty_n(start_for_interStage1_U0_empty_n),
    .if_read(interStage1_U0_ap_ready)
);

fit_start_for_interStage2_U0 start_for_interStage2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_interStage2_U0_din),
    .if_full_n(start_for_interStage2_U0_full_n),
    .if_write(readStage_U0_start_write),
    .if_dout(start_for_interStage2_U0_dout),
    .if_empty_n(start_for_interStage2_U0_empty_n),
    .if_read(interStage2_U0_ap_ready)
);

fit_start_for_finalStage_U0 start_for_finalStage_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_finalStage_U0_din),
    .if_full_n(start_for_finalStage_U0_full_n),
    .if_write(readStage_U0_start_write),
    .if_dout(start_for_finalStage_U0_dout),
    .if_empty_n(start_for_finalStage_U0_empty_n),
    .if_read(finalStage_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

assign ap_done = finalStage_U0_ap_done;

assign ap_idle = (readStage_U0_ap_idle & interStage2_U0_ap_idle & interStage1_U0_ap_idle & finalStage_U0_ap_idle);

assign ap_ready = readStage_U0_ap_ready;

assign finalStage_U0_ap_continue = ap_continue;

assign finalStage_U0_ap_start = start_for_finalStage_U0_empty_n;

assign input_r_TREADY = readStage_U0_input_r_TREADY;

assign interStage1_U0_ap_continue = 1'b1;

assign interStage1_U0_ap_start = start_for_interStage1_U0_empty_n;

assign interStage2_U0_ap_continue = 1'b1;

assign interStage2_U0_ap_start = start_for_interStage2_U0_empty_n;

assign output_r_TDATA = finalStage_U0_output_r_TDATA;

assign output_r_TVALID = finalStage_U0_output_r_TVALID;

assign readStage_U0_ap_continue = 1'b1;

assign readStage_U0_ap_start = ap_start;

assign readStage_U0_start_full_n = (start_for_interStage2_U0_full_n & start_for_interStage1_U0_full_n & start_for_finalStage_U0_full_n);

assign start_for_finalStage_U0_din = 1'b1;

assign start_for_interStage1_U0_din = 1'b1;

assign start_for_interStage2_U0_din = 1'b1;

endmodule //fit
